name: "Build"
on:
  pull_request:
  push:
    branches:
      main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-build:
    strategy:
      matrix:
        runtime: [ osx-arm64 ]
        include:

        - runtime: osx-arm64
          os: macos-14

      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build hevm
        run: nix build .#ci -L
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1      
          #- name: print solc
          #run: echo "Testing!" && nix shell -c "which solc && file `which solc` && solc --version"

